// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klxbexyxqajftjvmnisu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtseGJleHl4cWFqZnRqdm1uaXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODQ5NzAsImV4cCI6MjA2ODg2MDk3MH0.HTBVduVxOMGPDpd0J8j9D1JchbSPfy9zOZEo6QXi0aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});